[package]
name = "hunt"
description = "Simple command to search a file/folder by name on the entire drive."
documentation = "https://github.com/LyonSyonII/hunt-rs"
repository = "https://github.com/LyonSyonII/hunt-rs"
keywords = ["algorithms", "filesystem"]
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "1.5.11"
authors = ["Liam G <liam.garriga@tutanota.com>"]
edition = "2021"

[dependencies]
clap = { version = "3.2.7", features = ["derive"] }
directories = "4.0.1"
rayon = "1.5.3"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
derive-new = "0.5.9"
mimalloc = { version = "0.1.29", default-features = false }
colored = { version = "2.0.0", features = [] }

[profile.release]
lto = "thin"
